{{-- 
@extends('master')

@section('konten')
  <h4>Selamat Datang <b>{{Auth::user()->name}}</b>, Anda Login sebagai <b>{{Auth::user()->role}}</b>.</h4>
@endsection --}}


@extends('master')

@section('konten')
<div class="font-sans bg-gray-100 px-4 py-12">
  <div class="grid lg:grid-cols-2 gap-12 lg:max-w-6xl max-w-2xl mx-auto">
    <div class="text-left">
      <h2 class="text-gray-800 text-3xl font-bold mb-6">Visi</h2>
      <p class="mb-4 text-sm text-gray-500"> Terwujudna lulusan yang cerdas , beriman & bertaqwa , berjiwa wirausaha , siap kerja dan berakhlak mulia.</p>
      <h2 class="text-gray-800 text-3xl font-bold mb-6">Misi</h2>
      <p class="text-sm text-gray-500">Melatih beranggung jawab terhadap dirina sendiri dan masyarakat.
        Menanamkan kepada peserata didik iman dan taqwa kepada Allah SWT.
        Membekali lulusan , menjadi tenaga kerja terampil, profesional, yang produktif dan bermanfaat bagi diri dan masyarakat.
        Membekali lulusan untuk melanjutkan ke pendidikan yang lebih tinggi. </p>
    </div>
    <div>
      <img src="https://readymadeui.com/management-img.webp" alt="Placeholder Image" class="rounded-lg object-contain w-full h-full" />
    </div>
  </div>
</div>

<div class="bg-gray-50 p-8 min-h-[350px] flex flex-col items-center justify-center font-sans">
  <h2 class="text-gray-800 text-3xl font-bold mb-16 text-center">Statistik</h2>
  <div class="grid lg:grid-cols-4 sm:grid-cols-2 gap-6 max-lg:gap-12">
    <div class="text-center">
      <h3 class="text-gray-800 text-4xl font-extrabold">35</h3>
      <p class="text-base font-bold mt-4">Total Guru</p>
      <p class="text-sm text-gray-500 mt-2">The total number of registered users on the platform.</p>
    </div>
    <div class="text-center">
      <h3 class="text-gray-800 text-4xl font-extrabold">250</h3>
      <p class="text-base font-bold mt-4">Total Siswa</p>
      <p class="text-sm text-gray-500 mt-2">The total revenue generated by the application.</p>
    </div>
    <div class="text-center">
      <h3 class="text-gray-800 text-4xl font-extrabold">30</h3>
      <p class="text-base font-bold mt-4">Total Kelas</p>
      <p class="text-sm text-gray-500 mt-2">The level of user engagement with the application's content and features.</p>
    </div>
    <div class="text-center">
      <h3 class="text-gray-800 text-4xl font-extrabold">25</h3>
      <p class="text-base font-bold mt-4">Total Mata Pelajaran</p>
      <p class="text-sm text-gray-500 mt-2">The percentage of time the server has been operational and available.</p>
    </div>
  </div>
</div>

@endsection